name: Update badges

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Badges - Readme
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: python main.py

      - name: autocommit
        uses: stefanzweifel/git-auto-commit-action@v4